### ISSUE TITLE
seek help

### ISSUE THREAD

**Issue by Didi-cH** [KiLJ4EdeN/CINC_2016_Submission#1]
How did you extract features from the heart sound database? Could you provide 'pcg.mat' or 'pcgT.mat'?

**Comment by KiLJ4EdeN** [comment]
Hello,
You can download the dataset from https://physionet.org/content/challenge-2016/1.0.0/.
There are two sets to download, Train set which I save into pcg.mat and Test set that is the pcgT.mat.
No features were extracted from the signals, All you need to do is load the signal and label them accordingly by opening the .hea files associated with each recording. The first 10000 was used so it would be compatible with the whole database.

> How did you extract features from the heart sound database? Could you provide 'pcg.mat' or 'pcgT.mat'?
